networks:
  appnet:
    name: pocketc_appnet

services:
  mysql:
    image: mysql:8.4
    env_file: [ .env ]
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} --silent" ]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped
    networks: [appnet]

  redis:
    image: redis:7-alpine
    env_file: [ .env ]
    command: >
        sh -lc 'exec redis-server --appendonly yes $${REDIS_PASSWORD:+--requirepass $${REDIS_PASSWORD}}'
    volumes: [redis-data:/data]
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli $${REDIS_PASSWORD:+-a $${REDIS_PASSWORD}} ping | grep PONG" ]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped
    networks: [appnet]

  redis_ai:
    image: redis:7-alpine
    env_file: [ .env ]
    command: >
        sh -lc 'exec redis-server --port 6379 $${REDIS_PASSWORD:+--requirepass $${REDIS_PASSWORD}}'
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli $${REDIS_PASSWORD:+-a $${REDIS_PASSWORD}} ping | grep PONG" ]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: always
    networks: [appnet]

  backend:
    build: { context: ./pocketc_backend, dockerfile: Dockerfile }
    image: app:latest
    depends_on:
      mysql: { condition: service_healthy }
      redis: { condition: service_healthy }
      ai: { condition: service_started }
    expose: ["8080"]
    env_file: [ .env ]
    restart: unless-stopped
    networks: [appnet]

  ai:
    build: { context: ./pocketc_ai, dockerfile: Dockerfile }
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      mysql: { condition: service_healthy }
      redis_ai: { condition: service_healthy }
    env_file: [ .env ]
    expose: ["8000"]
    networks: [appnet]

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    depends_on: [backend, mysql, redis, ai]
    ports: ["80:80", "443:443", "3306:3306", "6379:6379"]
    volumes:
      - ./pocketc_backend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped
    networks: [appnet]

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    user: root
    environment:
      JENKINS_OPTS: --prefix=/jenkins
    volumes:
      - /opt/pocketc:/opt/pocketc:ro
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/libexec/docker/cli-plugins/docker-compose:/usr/libexec/docker/cli-plugins/docker-compose:ro
    networks: [appnet]

  worker:
    build: ./pocketc_ai/
    command: celery -A app.celery_app.celery worker -l info --concurrency=4
    depends_on:
      mysql: { condition: service_healthy }
      redis_ai: { condition: service_healthy }
    env_file: [ .env ]
    environment:
      CELERY_BROKER_URL: "redis://:${REDIS_PASSWORD}@redis_ai:6379/0"
      CELERY_RESULT_BACKEND: "redis://:${REDIS_PASSWORD}@redis_ai:6379/1"
    networks: [appnet]

  beat:
    build: ./pocketc_ai/
    command: celery -A app.celery_app.celery beat -l info
    depends_on:
      mysql: { condition: service_healthy }
      redis_ai: { condition: service_healthy }
    env_file: [ .env ]
    environment:
      CELERY_BROKER_URL: "redis://:${REDIS_PASSWORD}@redis_ai:6379/0"
      CELERY_RESULT_BACKEND: "redis://:${REDIS_PASSWORD}@redis_ai:6379/1"
    networks: [appnet]

  flower:
    build: ./pocketc_ai/
    command: sh -lc 'celery -A app.celery_app.celery flower --port=5555 \
                    --broker="$CELERY_BROKER_URL" --result-backend="$CELERY_RESULT_BACKEND"'
    ports:
      - "5555:5555"
    depends_on:
      mysql: { condition: service_healthy }
      redis_ai: { condition: service_healthy }
    env_file: [ .env ]
    environment:
      CELERY_BROKER_URL: "redis://:${REDIS_PASSWORD}@redis_ai:6379/0"
      CELERY_RESULT_BACKEND: "redis://:${REDIS_PASSWORD}@redis_ai:6379/1"
    networks: [appnet]

volumes:
  mysql-data:
  redis-data:
  jenkins_home:
    external: true
