spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:pocketcdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate.hbm2ddl.drop_constraints: false

  # Redis 완전 비활성화 (자동 설정 제외)
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

  # S3 비활성화
  cloud:
    aws:
      s3:
        enabled: false

# 테스트용 JWT 시크릿(가짜 값)
jwt:
  secret: test-secret-only
