services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file: .env
    depends_on: [redis]
    ports: ["8000:8000"]

  worker:
    build: .
    command: celery -A app.celery_app.celery worker -l info --concurrency=4
    env_file: .env
    depends_on: [redis]

  beat:
    build: .
    command: celery -A app.celery_app.celery beat -l info
    env_file: .env
    depends_on: [redis]

  flower:
    build: .
    command: celery -A app.celery_app.celery flower --port=5555
    env_file: .env
    environment:
      - FLOWER_BASIC_AUTH=${FLOWER_BASIC_AUTH}
    ports:
      - "5555:5555"
    depends_on: [redis]

  redis:
    image: redis:7-alpine
    container_name: pocketc_redis
    command: redis-server --port 6379
    ports:
      - "6379:6379"
    restart: always